{% set name = "geomeTRIC" %}
{% set version = "1.0.1a0" %}
{% set sha256 = "983ffbfc6d5db7701a9dc4649bfe4c19e28349e8445da2402657a4bc8350899c" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/robertodr/{{ name }}/archive/vlx.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: {{ build }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - geometric-optimize = geometric.optimize:main

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - {{ pin_compatible('numpy', lower_bound='1.18') }}
    - networkx
    - python
    - six

test:
  imports:
    - geometric
  requires:
    - pytest
    - rdkit
    - openmm
    - ase
    - xtb-python
  commands:
    - $PYTHON -m pytest --pyargs geometric -v -k json

about:
  home: http://github.com/leeping/geomeTRIC/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Molecular geometry optimizer in the TRIC coordinate system.'
  dev_url: http://github.com/leeping/geomeTRIC/

extra:
  recipe-maintainers:
    - robertodr
    - leeping
    - dgasmith
    - yudongqiu
