@echo off
if defined KMP_DUPLICATE_LIB_OK (
    set "_CONDA_BACKUP_KMP_DUPLICATE_LIB_OK=%KMP_DUPLICATE_LIB_OK%"
) else (
    set "_CONDA_BACKUP_KMP_DUPLICATE_LIB_OK="
)
set "KMP_DUPLICATE_LIB_OK=TRUE"
