CONDA_BUILD_SYSROOT:
  #- /Users/runner/MacOSX10.9.sdk     # [osx] # retired Oct 2020
  - /Users/runner/MacOSX10.10.sdk  # [osx]

mpi:
  - msmpi    # [win]
  - mpich    # [not win]
  - openmpi  # [not win]

python:
  - 3.10  # EOL: 04 Oct 2026
  - 3.9   # EOL: 05 Oct 2025
  - 3.8   # EOL: 14 Oct 2024
  - 3.7   # EOL: 27 Jun 2023
  #- 3.6   # EOL: 23 Dec 2021
