MACOSX_DEPLOYMENT_TARGET:
  - '11.0'  # [osx]

cdt_name:
  - cos6  # [linux]

channel_sources:
  - conda-forge

cxx_compiler:
  - gxx      # [linux]
  - clangxx  # [osx]

cxx_compiler_version:
  - '12'  # [linux]
  - '18'  # [osx]

# the following pinnings are necessary to allow switching the BLAS/LAPACK
# implementation as runtime, thus replicating the behavior of conda-forge
# packages documented here:
# https://conda-forge.org/docs/maintainer/knowledge_base.html#how-it-works
libcblas:
  - 3.9 *netlib

liblapacke:
  - 3.9 *netlib

llvm_openmp:
  - '15'  # [win]
  - '18'  # [osx]

macos_machine:
  - arm64-apple-darwin20.0.0   # [osx and arm64]
  - x86_64-apple-darwin13.4.0  # [osx and x86_64]

numpy:
  - '1.21'  # [not py==311]
  - '1.23'  # [py==311]
  
mpi:
  - msmpi    # [win]
  - mpich    # [not win]
  - openmpi  # [not win]

python:
  - '3.8'   # EOL: 14 Oct 2024
  - '3.9'   # EOL: 05 Oct 2025
  - '3.10'  # EOL: 04 Oct 2026
  - '3.11'  # EOL: 24 Oct 2027

target_platform:
  - linux-64  # [linux]
  - win-64    # [win]
  - osx-arm64  # [osx and arm64]
  - osx-64     # [osx and x86_64]

CONDA_BUILD_SYSROOT:
  - /Users/runner/MacOSX11.0.sdk  # [osx]

