@echo off
if defined _CONDA_BACKUP_KMP_DUPLICATE_LIB_OK (
    set "KMP_DUPLICATE_LIB_OK=%_CONDA_BACKUP_KMP_DUPLICATE_LIB_OK%"
    set "_CONDA_BACKUP_KMP_DUPLICATE_LIB_OK="
) else (
    set "KMP_DUPLICATE_LIB_OK="
)
if defined _CONDA_BACKUP_PYTHONUTF8 (
    set "PYTHONUTF8=%_CONDA_BACKUP_PYTHONUTF8%"
    set "_CONDA_BACKUP_PYTHONUTF8="
) else (
    set "PYTHONUTF8="
)
