name: Deploy Python packages

on:
  push:
    branches:
      - main
    paths:
      - conda-recipes/geometric/meta.yaml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Deploy to Anaconda.org
    runs-on: ubuntu-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        recipe:
          - geometric

    steps:
      - uses: actions/checkout@v4

      - name: Build summary
        run: |
          echo "Workflow triggered for recipe: conda-recipes/${{ matrix.recipe }}/meta.yaml"

      - uses: conda-incubator/setup-miniconda@v3
        with:
          conda-remove-defaults: true
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: deploy
          environment-file: .github/deploy.yml
          use-mamba: true

      - name: Build and upload ${{ matrix.recipe }} Python package
        id: condabuild
        continue-on-error: true
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE/conda-recipes
          conda build \
                --token $ANACONDA_TOKEN \
                --user veloxchem \
                --label main \
                --verify \
                -c conda-forge \
                ${{ matrix.recipe }}
